# Generated by Django 5.1.1 on 2024-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "женский"), ("male", "мужской")],
                help_text="выберите пол",
                null=True,
                verbose_name="пол",
            ),
        ),
    ]
