# Generated by Django 5.1.1 on 2024-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватар",
                null=True,
                upload_to="users/",
                verbose_name="аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите email",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "женский"), ("male", "мужской")],
                help_text="Выберите пол",
                null=True,
                verbose_name="пол",
            ),
        ),
    ]
