# Generated by Django 5.1.1 on 2024-09-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_avatar_alter_user_email_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="статус аккаунта"),
        ),
        migrations.AddField(
            model_name="user",
            name="verify_key",
            field=models.CharField(blank=True, null=True),
        ),
    ]
