# Generated by Django 5.1.1 on 2024-09-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_verified_user_verify_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
