# Generated by Django 5.1.1 on 2024-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Вы можете добавить фото к заметке.",
                null=True,
                upload_to="notes/",
                verbose_name="фото",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="body",
            field=models.TextField(
                help_text="Укажите содержание заметки.",
                verbose_name="содержание заметки",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="topic",
            field=models.CharField(
                help_text="Укажите заголовок заметки.",
                max_length=50,
                verbose_name="заголовок",
            ),
        ),
    ]
