# Generated by Django 5.1.1 on 2024-09-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_note_image_alter_note_body_alter_note_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body",
            field=models.TextField(verbose_name="содержание заметки"),
        ),
        migrations.AlterField(
            model_name="note",
            name="topic",
            field=models.CharField(max_length=50, verbose_name="заголовок"),
        ),
    ]
